#!/bin/bash

pip install torchcontrib
pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
pip install librosa
pip install https://github.com/PytorchLightning/pytorch-lightning/archive/0.9.0.zip --upgrade
pip install pytorch-model-summary

